CREATE TABLE drivers (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    driver_profile_id BIGiNT NOT NULL,
    truck_id BIGINT NOT NULL,

    CONSTRAINT fk_drivers_user_id
                     FOREIGN KEY (user_id)
                     REFERENCES users(id),
    CONSTRAINT fk_drivers_driver_profile_id
                     FOREIGN KEY (driver_profile_id)
                     REFERENCES driver_profiles(id),
    CONSTRAINT fk_drivers_truck_id
                     FOREIGN KEY (truck_id)
                     REFERENCES trucks(id)
);