CREATE TABLE customer_profiles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(20) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    phone_number VARCHAR(15) NOT NULL UNIQUE,
    company_name VARCHAR(100) NOT NULL,
    address VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL, UNIQUE,

    CONSTRAINT fk_customer_user_id
                      FOREIGN KEY (user_id)
                      REFERENCES users(id)
);