CREATE TABLE driver_profiles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(20) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    phone_number VARCHAR(15) NOT NULL UNIQUE,
    license_number VARCHAR(10) NOT NULL UNIQUE,
    address VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL UNIQUE,
    truck_id BIGINT NOT NULL,

    CONSTRAINT fk_user_id_driver_profiles
                             FOREIGN KEY (user_id)
                             REFERENCES users(id),
    CONSTRAINT fk_truck_id_driver_profiles
                             FOREIGN KEY (truck_id)
                             REFERENCES trucks(id)
);