CREATE TABLE customers (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    customer_profile_id BIGINT NOT NULL,

    CONSTRAINT fk_customers_user_id
                       FOREIGN KEY (user_id)
                       REFERENCES users(id),
    CONSTRAINT fk_customers_customer_profiles
                       FOREIGN KEY (customer_profile_id)
                       REFERENCES customer_profiles(id)
);